update

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -53,8 +53,10 @@ jobs:
           creds: ${{ secrets.AZURE_CREDS }}
 
     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-    - name: Terraform Init
-      run: terraform init
+    - name: Terraform Init/Plan
+      run: |
+        terraform init
+        terraform plan
 
     # Checks that all Terraform configuration files adhere to a canonical format
     # Will fail the build if not
@@ -63,28 +65,28 @@ jobs:
       # run: terraform fmt -autocorrect
     # Generates an execution plan for Terraform
     # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
-    - name: Terraform Plan
-      id: tf-plan
-      run: |
-        export exitcode=0
-        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+    # - name: Terraform Plan
+    #   id: tf-plan
+    #   run: |
+    #     export exitcode=0
+    #     terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
 
-        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+    #     echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
         
-        if [ $exitcode -eq 1 ]; then
-          echo Terraform Plan Failed!
-          exit 1
-        else 
-          exit 0
-        fi
+    #     if [ $exitcode -eq 1 ]; then
+    #       echo Terraform Plan Failed!
+    #       exit 1
+    #     else 
+    #       exit 0
+    #     fi
         
-    # Save plan to artifacts  
-    - name: Publish Terraform Plan
-      uses: actions/upload-artifact@v3
-      with:
-        name: tfplan
-        path: tfplan
-        
+    # # Save plan to artifacts  
+    # - name: Publish Terraform Plan
+    #   uses: actions/upload-artifact@v3
+    #   with:
+    #     name: tfplan
+    #     path: tfplan
+
     # Create string output of Terraform Plan
     - name: Create String Output
       id: tf-plan-string
@@ -130,7 +132,7 @@ jobs:
     name: 'Terraform Apply'
     if: github.ref == 'refs/heads/AzSample' 
     runs-on: ubuntu-latest
-    environment: production
+    environment: dev
     needs: [terraform-plan]
     
     steps:
@@ -152,11 +154,11 @@ jobs:
       run: terraform init
 
     # Download saved plan from artifacts  
-    - name: Download Terraform Plan
-      uses: actions/download-artifact@v3
-      with:
-        name: tfplan
+    # - name: Download Terraform Plan
+    #   uses: actions/download-artifact@v3
+    #   with:
+    #     name: tfplan
 
     # Terraform Apply
     - name: Terraform Apply
-      run: terraform apply -auto-approve tfplan
+      run: terraform apply # -auto-approve tfplan
